import HomePageContainer from '@/components/HomePage/HomePageContainer/HomePageContainer';
import Head from 'next/head';

export default function Home() {
  return (
    <>
      <Head>
        <title>Codenames</title>
        {/* <meta name="description" content="Generated by create next app" /> */}
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <HomePageContainer />
      </main>
    </>
  );
}
